### ISSUE TITLE
DEHB update design (async strategy)

### ISSUE THREAD

**Issue by drpriscu** [automl/HPOBench#159] opened 2022-09-17 17:30 UTC
Hello, According to the paper "DEHB: Evolutionary Hyperband for Scalable, Robust, and Efficient Hyperparameter Optimization," DEHB employs an immediate update design for DE by utilising the AsyncDE class. However, despite passing the async strategy argument in DEHB, it does not change the async strategy of the AsyncDE class, which by default is 'deferred.'  How was this mitigated as I see that the async_strategy argument is passed? 

The DE class currently only uses deferred updates. If one would like to compare DEHB and its DE component as separate optimisers for optimising a model's validation score, would the update design of deferred vs immediate have a significant impact on the final validation score or simply the wall-clock time? I'd like to compare DE and DEHB using the same update design, and the paper suggests that the immediate update design outperforms deferred DE.

**Comment by Neeratyoy** [comment] 2022-09-18 21:55
Duplicate of the [issue in DEHB](https://github.com/automl/DEHB/issues/22), which has been addressed already.

**Closed as completed by Neeratyoy** 2022-09-18 21:55 UTC
